### ISSUE TITLE
Listen to WM_INPUT

### ISSUE THREAD

**Issue by siikamiika** [Jonesey13/multiinput-rust#2]
The `apitest.rs` example uses a lot of CPU cycles when it repeatedly checks if there are new events. I think you are supposed to listen to `WM_INPUT` messages and check for new raw input event after them, but I don't know how it should be done in Rust.

Example in AutoHotkey: https://github.com/siikamiika/scripts/blob/6502dc27fe301b32b1012d7a241f425ef3000b5b/windows/remotekeyboard.ahk#L20

**Comment by Jonesey13** [comment]
This is a very old issue but I think I should try to answer it for future reference;

1. The approach used in this library is to read raw input events from the window's input buffer , rather than repeatedly checking for messages from the event loop ([this is the winapi function for this](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getrawinputbuffer)).
1. The apitest thread did run continuously without waiting but this has now been fixed.
